import type { Metadata } from 'next';
import localFont from 'next/font/local';

import QueryProvider from '@/libs/detail/QueryProvider';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  weight: '45 920',
  style: 'normal',
  display: 'swap',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`layout font-pretendard antialiased ${pretendard.variable}`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
