import { create } from "zustand";
import { MakeStoreState } from "@/types/make/i-makeState";

export const useMakeStore = create<MakeStoreState>((set) => ({
  type: '',
  name: '',
  description: '',
  dateTime: '',
  registrationEnd: '',
  location: '',
  isOnline: false,
  participantCount: 0,
  capacity: 0,
  image: '',
  recruitmentStart: '',
  moimStart: '',
  moimEnd: '',
  minParticipants: 0,
  maxParticipants: 0,
  setType: (type) => set({ type }),
  setName: (name) => set({ name }),
  setDescription: (description) => set({ description }),
  setLocation: (location) => set({ location }),
  toggleIsOnline: () => set((state) => ({ isOnline: !state.isOnline })),
  setDateTime: (dateTime) => set({ dateTime }),
  setRegistrationEnd: (registrationEnd) => set({ registrationEnd }),
  setRecruitmentStart: (recruitmentStart) => set({ recruitmentStart }),
  setMoimStart: (moimStart) => set({ moimStart }),
  setMoimEnd: (moimEnd) => set({ moimEnd }),
  setCapacity: (capacity) => set({ capacity }),
  setMinParticipants: (minParticipants) => set({ minParticipants }),
  setMaxParticipants: (maxParticipants) => set({ maxParticipants }),
  setImage: (image) => set({ image }),
  reset: () => set({
    type: '',
    name: '',
    description: '',
    dateTime: '',
    registrationEnd: '',
    location: '',
    isOnline: false,
    participantCount: 0,
    capacity: 0,
    image: '',
    recruitmentStart: '',
    moimStart: '',
    moimEnd: '',
    minParticipants: 0,
    maxParticipants: 0,
  }),
}));